# -*- coding: utf-8 -*-
"""Assignment_1_AI1103

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yiV4VOO3hWf2Rgs4ojnb11jmnACVXjal
"""

import random as rand

throws = 7

simulations = 1000000

i=0
sum=0

while (i < simulations):
  j=0
  k=0
  while (j < throws):
    X = rand.randint(1,6)
    if (X==5):  k+=1
    j=j+1
  if (k==2):  sum+=1
  i=i+1

Pr=sum/simulations

print("The Probability of getting 5 exactly twice in 7 throws of a die by simulations: ",Pr,"\n")
print("The Probability of getting 5 exactly twice in 7 throws of a die by calculation: 0.234428\n")
print("Therefore, the result obtained by the simulations is almost equal to the value got by actual calculation\n")